dataset_ratio: 1.0
batch_size: 16
scale: 1.0
epochs: 200

scales:
  stress2: 1000.

unit_scales:
  stress2: 1.

model:
  name: HieraDPT
  out_chans: [3]
  pretrained_model: "DT_Ultra_1/checkpoints/last.ckpt"
  LoRA: True

  hiera:
    decoder: "QUpsampling"
    decoder_embed_dim: 512
    decoder_num_heads: 16
    decoder_depth: 8

dataset:
  output_type: ["stress2"]

optimizer:
  name: AdamW
  lr: 0.001

metric:
  PN_thresh: 0.001
  TF_abs_error_thresh: 0.01

scheduler:
  name: linear_cosine
  warmup: 2000