dataset_ratio: 1.0
batch_size: 16
scale: 1.0
epochs: 100

scales:
  disp: 10.
  cnorm: 1000.
  stress: 1000.
  stress2: 1000.

unit_scales:
  disp: 1000.
  cnorm: 1.
  stress: 1.
  stress2: 1.

model:
  name: HieraDPT
  out_chans: [3, 3, 3, 3]
  pretrained_model: "DT_Ultra_1/checkpoints/last.ckpt"
  LoRA: True

  hiera:
    decoder: "QUpsampling"
    decoder_embed_dim: 512
    decoder_num_heads: 16
    decoder_depth: 8

dataset:
  output_type: ["disp", "cnorm", "stress1", "stress2"]
  normalization: False

optimizer:
  name: AdamW
  lr: 0.001

metric:
  PN_thresh: 0.001
  TF_abs_error_thresh: 0.01

scheduler:
  name: linear_cosine
  warmup: 2000