dataset_ratio: 1.0

model:
  name: ViT
  out_chans: 1
  pretrained_model: "exp/MAE_ViT_Pretrain_75/checkpoints/last.ckpt"

dataset:
  output_type: "depth"

optimizer:
  name: AdamW
  lr: 0.001

scheduler:
  name: linear_cosine
  warmup: 2000